#!/usr/bin/python
# -*- coding: utf-8 -*-
# https://github.com/wktr/pyweather

import getopt
import json
import platform
import sys
import time
import urllib2

API_URL = 'http://api.openweathermap.org/data/2.5/weather?q=%s&units=%s'
TIME_FMT = '%a %b %d %H:%M:%S %Z %Y'

BLACK = '\033[30;1m'
RED = '\033[31;1m'
GREEN = '\033[32;1m'
YELLOW = '\033[33;1m'
BLUE = '\033[34;1m'
MAGENTA = '\033[35;1m'
CYAN = '\033[36;1m'
WHITE = '\033[37;1m'
RESET = '\033[0m'

BG_COL = ''
TEXT_COL = BLUE
SND_COL = WHITE
DATA_COL = YELLOW
DELIM = '%s=>' % MAGENTA
CITY_COL = RED
SYM_COL = GREEN

SUN = '\033[33;1m\xe2\x98\x80'
MOON = '\033[36m\xe2\x98\xbd'
CLOUDS = '\033[37;1m\xe2\x98\x81'
RAIN = '\xe2\x98\x94'
FOG = '\xe2\x96\x92'
MIST = '\033[37m\xe2\x96\x92'
SNOW = '\033[37m\xe2\x9d\x84'
THUNDERSTORM = '\033[33m\xe2\x9a\xa1'

if platform.system() == 'Windows':
	BG_COL = TEXT_COL = SND_COL = DATA_COL = CITY_COL = SYM_COL = RESET = ''
	DELIM = '=>'

def get_scale(units):
	conv = {'imperial': 'F', 'metric': 'C'}
	return u'\u00b0%s' % (conv[units] if conv.has_key(units) else 'K')

def get_speed_unit(units):
	return 'mph' if units == 'imperial' else 'm/s'

def get_period(sunrise, sunset):
	now = int(time.time())
	return 'Night' if now >= sunset or now <= sunrise else 'Day'

def get_api_data(location, units):
	u = urllib2.urlopen(API_URL % (location, units))
	lines = u.read()
	u.close()
	return lines

def get_icon(period, sky, units):
	conv = {
		'Clear': MOON if period == 'Night' else SUN,
		'Clouds': CLOUDS,
		'Rain': RAIN,
		'Drizzle': RAIN,
		'Fog': FOG,
		'Mist': MIST,
		'Snow': SNOW,
		'Thunderstorm': THUNDERSTORM
	}
	if not symbols:
		return sky
	return conv[sky].decode('utf-8') if conv.has_key(sky) else sky

def get_wind_dir(wind_deg):
	directions = 'N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW'.split()
	return directions[int((wind_deg + 11.25) / 22.5 % 16)]

def process_weather(location, units, symbols):
	# Set the scale.
	scale = get_scale(units)

	# Set the wind speed unit.
	speed_unit = get_speed_unit(units)

	# Fetch weather data.
	lines = get_api_data(location, units)
	winfo = json.loads(lines)

	# Process weather data.
	if winfo.has_key('message'):
		print winfo['message']
		return
	city = winfo['name']
	country = winfo['sys']['country']
	temp = winfo['main']['temp']
	humidity = winfo['main']['humidity']
	pressure = winfo['main']['pressure']
	sky = winfo['weather'][0]['main']
	sunrise = winfo['sys']['sunrise']
	sunset = winfo['sys']['sunset']
	wind = winfo['wind']['speed']
	wind_deg = winfo['wind']['deg']
	dt = winfo['dt']

	# Set the period.
	period = get_period(sunrise, sunset)

	# Set the icons.
	icon = get_icon(period, sky, units)

	write = sys.stdout.write
	write('%s%s ' % (BG_COL, TEXT_COL))

	tms = time.strftime(TIME_FMT, time.localtime(dt))
	write('Time updated %s%s %s \n%s ' % (DELIM, DATA_COL, tms, TEXT_COL))

	write('Current weather in %s%s, %s %s%s %s %s%s %s  %s%s \n%s ' % (CITY_COL,
		city, country, DELIM, DATA_COL, temp, SYM_COL, scale, icon, SND_COL,
		period, TEXT_COL))

	write('Humidity %s%s %s %s%% \n%s ' % (DELIM, DATA_COL, humidity, SYM_COL,
		TEXT_COL))

	write('Wind %s%s %s %s%s %s(%s)\n%s ' % (DELIM, DATA_COL, wind, SYM_COL,
		speed_unit, SND_COL, get_wind_dir(wind_deg), TEXT_COL))

	write('Pressure %s%s %s %shPa' % (DELIM, DATA_COL, pressure, SYM_COL))
	print RESET

# Display current weather.
if __name__ == '__main__':
	opts, args = getopt.getopt(sys.argv[1:], 'u:t')
	units = 'imperial'
	symbols = True
	for opt, val in opts:
		if opt == '-u':
			units = val
		elif opt == '-t':
			symbols = False
	if platform.system() == 'Windows':
		symbols = False
	if not args:
		print ('usage: %s [-u imperial|metric|kelvin] [-t]'
			+ ' city[,country]') % sys.argv[0]
		print 'example: %s -u metric "New York,NY" "Beijing,CN"' % sys.argv[0]
		exit()
	for location in args:
		process_weather(location, units, symbols)
