#!/usr/bin/python
# -*- coding: utf-8 -*-
# Port of 'ansiweather': https://github.com/fcambus/ansiweather

import json
import sys
import time
import urllib2

API_URL = 'http://api.openweathermap.org/data/2.5/weather?q=%s&units=%s'
TIME_FMT = '%a %b %d %H:%M:%S %Z %Y'

BLACK = '\033[30;1m'
RED = '\033[31;1m'
GREEN = '\033[32;1m'
YELLOW = '\033[33;1m'
BLUE = '\033[34;1m'
MAGENTA = '\033[35;1m'
CYAN = '\033[36;1m'
WHITE = '\033[37;1m'
RESET = '\033[0m'

BG_COL = ''
TEXT_COL = BLUE
SND_COL = WHITE
DATA_COL = YELLOW
DELIM = '%s=>' % MAGENTA
CITY_COL = RED
SYM_COL = GREEN

SUN = '\033[33;1m\xe2\x98\x80'
MOON = '\033[36m\xe2\x98\xbd'
CLOUDS = '\033[37;1m\xe2\x98\x81'
RAIN = '\xe2\x98\x94'
FOG = '\xe2\x96\x92'
MIST = '\033[37m\xe2\x96\x92'
SNOW = '\033[37m\xe2\x9d\x84'
THUNDERSTORM = '\033[33m\xe2\x9a\xa1'

def get_scale(units):
	conv = {'imperial': 'F', 'metric': 'C'}
	return u'\u00b0%s' % (conv[units] if conv.has_key(units) else 'K')

def get_speed_unit(units):
	return 'mph' if units == 'imperial' else 'm/s'

def get_period(sunrise, sunset):
	now = int(time.time())
	return 'Night' if now >= sunset or now <= sunrise else 'Day'

def get_api_data(location, units):
	u = urllib2.urlopen(API_URL % (location, units))
	lines = u.read()
	u.close()
	return lines

def get_icon(period, sky, units):
	conv = {
		'Clear': MOON if period == 'Night' else SUN,
		'Clouds': CLOUDS,
		'Rain': RAIN,
		'Fog': FOG,
		'Mist': MIST,
		'Snow': SNOW,
		'Thunderstorm': THUNDERSTORM
	}
	if not symbols:
		return sky
	return conv[sky].decode('utf-8') if conv.has_key(sky) else sky

def process_weather(location, units, symbols):
	# Set the scale.
	scale = get_scale(units)

	# Set the wind speed unit.
	speed_unit = get_speed_unit(units)

	# Fetch weather data.
	lines = get_api_data(location, units)
	winfo = json.loads(lines)

	# Process weather data.
	city = winfo['name']
	temp = winfo['main']['temp']
	humidity = winfo['main']['humidity']
	pressure = winfo['main']['pressure']
	sky = winfo['weather'][0]['main']
	sunrise = winfo['sys']['sunrise']
	sunset = winfo['sys']['sunset']
	wind = winfo['wind']['speed']
	dt = winfo['dt']

	# Set the period.
	period = get_period(sunrise, sunset)

	# Set the icons.
	icon = get_icon(period, sky, units)

	write = sys.stdout.write
	write('%s%s ' % (BG_COL, TEXT_COL))

	tms = time.strftime(TIME_FMT, time.localtime(dt))
	write('Time updated %s%s %s \n%s ' % (DELIM, DATA_COL, tms, TEXT_COL))

	write('Current weather in %s%s %s%s %s %s%s %s  %s%s \n%s ' % (CITY_COL,
		city, DELIM, DATA_COL, temp, SYM_COL, scale, icon, SND_COL,
		period, TEXT_COL))

	write('Humidity %s%s %s %s%% \n%s ' % (DELIM, DATA_COL, humidity, SYM_COL,
		TEXT_COL))

	write('Wind %s%s %s %s%s \n%s ' % (DELIM, DATA_COL, wind, SYM_COL,
		speed_unit, TEXT_COL))

	write('Pressure %s%s %s %shPa' % (DELIM, DATA_COL, pressure, SYM_COL))
	print RESET

# Display current weather.
if __name__ == '__main__':
	location = 'New York,NY'
	units = 'imperial'
	symbols = True
	process_weather(location, units, symbols)
